# 服务器配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  port: 3278
  servlet:
    context-path: /emergency

# spring配置
spring:
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.emergency.entity
  # 全局配置
  global-config:
    db-config:
      schema: public  # 仅对 MP 自动 CRUD 生效
      # table-prefix: public.
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jasypt解密配置
jasypt:
  encryptor:
    password: ${OSS}
    key-obtention-iterations: 1649